spring:
  application:
    name: atlas
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.2.191:1234/test?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
#    driver-class-name: com.mysql.jdbc.Driver
#  main:
#    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: master,slave1
      master:
        type: org.apache.commons.dbcp2.BasicDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.2.191:3306/test?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
        #最大连接数
        maxPoolSize: 20
      slave1:
        type: org.apache.commons.dbcp2.BasicDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.2.190:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
        maxPoolSize: 20
    masterslave:
      load-balance-algorithm-type: round_robin # 配置从库选择策略，提供轮询与随机，这里选择用轮询//random 随机 //round_robin 轮询
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave1
    props:
      sql: # 开启SQL显示，默认值: false，注意：仅配置读写分离时不会打印日志！！！
        show: true


server:
  port: 9999